import type { Metadata } from 'next'
import './globals.css'
import '@/assets/css/_variables.css'
import '@/assets/css/global.css'
import MainLayout from "@/components/templates/main-layout";
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<Head>
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
				<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
			</Head>
			<body>
				<MainLayout>
				  	{ children }
				</MainLayout>
			</body>
		</html>
	)
}
