import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/assets/css/_variables.css'
import '@/assets/css/global.css'
import MainLayout from "@/components/templates/main-layout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MainLayout>
				  	{ children }
				</MainLayout>
			</body>
		</html>
	)
}
